### ISSUE TITLE
Gosec fails when running as pre commit hook

### ISSUE THREAD

**Issue by tonsV2** [TekWizely/pre-commit-golang#29]
My hook is configured as below

    - repo: https://github.com/tekwizely/pre-commit-golang
      rev: 645165368711be670d1945c15060e746f5ed15c6
      hooks:
        - id: go-sec-repo-pkg
          args:
            - "-exclude-generated"

It should be noted that running gosec from the command like works just fine. Specifically I'm using the below command successfully

    gosec -exclude-generated ./...

Both places gosec is installed using the below command

    go install github.com/securego/gosec/v2/cmd/gosec@master

When I try to use gosec using the hooks provided by this repository I get a bunch of the following errors

    ...
    Results:
    
    Golang errors in file: [/home/tons/IdeaProjects/dhis2/im-database-manager/cmd/serve/main.go]:
    
      > [line 33 : column 2] - could not import github.com/aws/aws-sdk-go-v2/feature/s3/manager (invalid package name: "")
    
      > [line 35 : column 11] - could not import github.com/aws/aws-sdk-go-v2/config (invalid package name: "")
    
      > [line 36 : column 2] - could not import github.com/aws/aws-sdk-go-v2/service/s3 (invalid package name: "")
    
      > [line 38 : column 2] - could not import github.com/dhis2-sre/im-database-manager/internal/handler (invalid package name: "")
    
      > [line 39 : column 2] - could not import github.com/dhis2-sre/im-database-manager/internal/server (invalid package name: "")
    
      > [line 40 : column 2] - could not import github.com/dhis2-sre/im-database-manager/pkg/config (invalid package name: "")
    
      > [line 41 : column 2] - could not import github.com/dhis2-sre/im-database-manager/pkg/database (invalid package name: "")
    
      > [line 42 : column 2] - could not import github.com/dhis2-sre/im-database-manager/pkg/storage (invalid package name: "")
    
      > [line 43 : column 17] - could not import github.com/dhis2-sre/im-manager/pkg/client (invalid package name: "")
    
      > [line 44 : column 13] - could not import github.com/dhis2-sre/im-user/pkg/client (invalid package name: "")
    
    
    Golang errors in file: [/home/tons/IdeaProjects/dhis2/im-database-manager/internal/apperror/apperror.go]:
    
      > [line 9 : column 2] - could not import github.com/gofrs/uuid (invalid package name: "")
    
    
    Golang errors in file: [/home/tons/IdeaProjects/dhis2/im-database-manager/internal/handler/authentication.go]:
    
      > [line 10 : column 2] - could not import github.com/dhis2-sre/im-user/swagger/sdk/models (invalid package name: "")
    
      > [line 12 : column 2] - could not import github.com/dhis2-sre/im-database-manager/internal/apperror (invalid package name: "")
    
      > [line 13 : column 2] - could not import github.com/dhis2-sre/im-database-manager/pkg/config (invalid package name: "")
    
      > [line 15 : column 2] - could not import github.com/lestrrat-go/jwx/jwa (invalid package name: "")
    
      > [line 16 : column 2] - could not import github.com/lestrrat-go/jwx/jwk (invalid package name: "")
    
      > [line 17 : column 2] - could not import github.com/lestrrat-go/jwx/jwt (invalid package name: "")
    ...

This happens both locally and when running on GitHub as an Action (which can be seen [here](https://github.com/dhis2-sre/im-database-manager/actions/runs/4155401344/jobs/7188459046))

Any idea what goes wrong?

**Comment by TekWizely** [comment]
Hi @tonsV2 and thanks or taking the time to report an issue.

First Q: Are you sure you want `go-sec-repo-pkg` ?

ie. Is your project an actual old-school go package (vs the new standard module format)?
ie. You do not have a go.mod file and each sub-folder in the project (if any) is a unique go package?

If not, and if you are indeed using the modern module format, please try the `go-sec-repo-mod` hook and see if you have any better luck.

The `*-pkg` hooks force `export GO111MODULE=off` which could break your compile if you're using modules.

Please also note that a quick googling for `go invalid package name: ""` shows that older versions fo gosec did not support multiple go.mod files
* https://github.com/securego/gosec/issues/501

This has since been fixed:
* https://github.com/cosmos/gosec/pull/23

BUT a comment on that issue seems relevant:
```
... and when use GO111MODULE=off then it is giving same error as mentioned by @WLun001
```

So it sound like, even though gosec fixed the multi module error, it may still fail for package mode.

**Comment by tonsV2** [comment]
@TekWizely thanks for the ping, I'll look this based on your feedback and report back here

**Comment by tonsV2** [comment]
@TekWizely it worked with `go-sec-repo-mod`. Thanks for your support!
